# Generated by Django 2.0 on 2018-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellsGun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.CharField(choices=[('lock', '枪锁'), ('stock', '枪托'), ('barrel', '枪杆')], max_length=10, verbose_name='产品名称'),
        ),
    ]
